version: '3'

services:
  app:
    build: ./
#    command: ./wait-for-postgres.sh db ./urllist-app
    ports:
      - 8080:8080
#    depends_on:
#      - db
#    environment:
#      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=pswrdroot
    ports:
      - 5432:5432